### ISSUE TITLE
添加服务端口可以自定义设置 固定8080始终不太好

### ISSUE THREAD

**Issue by david88558855** [SianHH/gostc-open#7]
添加服务端口可以自定义设置 固定8080始终不太好 比如使用 -p参数 设置新的端口

**Comment by SianHH** [comment]
第一次初始化会生成配置文件，修改data/config.yaml中的address

```yaml
address: 0.0.0.0:8080
auth-key: hlhpltxeaw0u8wwh
auth-exp: 168h0m0s
auth-renew: 2h0m0s
db-type: sqlite
sqlite:
    file: ./data/data.db
    log-level: info
mysql:
    host: 127.0.0.1
    port: 3306
    db: table_name
    user: root
    pwd: root
    prefix: gostc_
    extend: ?timeout=3s&readTimeout=3s&writeTimeout=3s&parseTime=true&loc=Local&charset=utf8mb4,utf8&useSSL=false
    log-level: info
```
